### ISSUE TITLE
Add the option to connect via ssh to the pi-hole instance

### ISSUE THREAD

**Issue by F3000** [joshspicer/pihole-mobile-app#8]

**Comment by joshspicer** [comment]
Hello! This is outside the scope of the app. I'm aiming to create something to "quick toggle" commonly accessed features of pi-hole. Certainly not trying to get 1:1 parity with the webapp (that's why the awesome webapp exists!).

There's plenty of SSH clients on the app store - I use [terminus](https://apps.apple.com/us/app/termius-ssh-client/id549039908) and it's great!
